language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install python-coveralls coverage
script:
  - coverage run --source mocurly setup.py test
after_success:
  - coveralls
